/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class Hour extends javax.swing.JFrame {
    
    private static final ArrayList<TimeTable> tuoTimeS = new ArrayList<TimeTable>();
    private static final ArrayList<TimeTable> tuoTimeE = new ArrayList<TimeTable>();
    private static final ArrayList<TimeTable> tueTimeS = new ArrayList<TimeTable>();
    private static final ArrayList<TimeTable> tueTimeE = new ArrayList<TimeTable>();
    
    private static final ArrayList<Tutor> tutor = new ArrayList<Tutor>();
    private static final ArrayList<Tutee> tutee = new ArrayList<Tutee>();
    
    private static final ArrayList<Students> students = new ArrayList<Students>();

    /**
     * Creates new form Hour
     */
    public Hour() {
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit?", "Tutor Center", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                } catch (ClassNotFoundException err) {
                    JOptionPane.showMessageDialog(null,err);
                }
       
                final String ID = "cseyou1";
                final String PW = "Cosc*ymfw";
                final String SERVER = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/cseyou1db";

                try
                {

                    Connection con = DriverManager.getConnection(SERVER,ID,PW);
                    Statement stmt = con.createStatement();

                    stmt.executeUpdate("DELETE FROM cseyou1db.Tutor_signin");
                    stmt.executeUpdate("DELETE FROM cseyou1db.Tutee_signin");



                }
                catch(SQLException error)
                {
                    JOptionPane.showMessageDialog(null,error);
                }
                System.exit(0);
                    }else {
                        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
                    }
                 
                        
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tutorTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tuteeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tutorBtn = new javax.swing.JButton();
        tutorIDIN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tutorDateIN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tuteeIDIN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tuteeDateIN = new javax.swing.JTextField();
        tuteeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tutorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Date", "Hours"
            }
        ));
        jScrollPane1.setViewportView(tutorTable);

        tuteeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Date", "Hours"
            }
        ));
        jScrollPane2.setViewportView(tuteeTable);

        jLabel1.setText("Tutor Hours");

        tutorBtn.setText("Search");
        tutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorBtnActionPerformed(evt);
            }
        });

        tutorIDIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorIDINActionPerformed(evt);
            }
        });

        jLabel3.setText("ID:");

        jLabel4.setText("mm-dd-yyyy:");

        jLabel6.setText("ID:");

        tuteeIDIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuteeIDINActionPerformed(evt);
            }
        });

        jLabel5.setText("mm-dd-yyyy:");

        tuteeBtn.setText("Search");
        tuteeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuteeBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Tutee Hours");

        jButton1.setText("<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tutorIDIN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tutorDateIN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(tutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tuteeIDIN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tuteeDateIN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tuteeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tutorIDIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(tutorDateIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tuteeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tuteeDateIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tuteeIDIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutorIDINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorIDINActionPerformed

    }//GEN-LAST:event_tutorIDINActionPerformed

    private void tuteeIDINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuteeIDINActionPerformed

    }//GEN-LAST:event_tuteeIDINActionPerformed

    private void tutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorBtnActionPerformed
        tuoTimeS.clear();
        tuoTimeE.clear();
        students.clear();

        String searchID = tutorIDIN.getText();
        String searchDate = tutorDateIN.getText();
        boolean checkID = false;
        boolean checkDate = false;
        if(searchID.isBlank() || searchID.isEmpty()){
            checkID= true;
        }
        if(searchDate.isBlank() || searchDate.isEmpty()){
            checkDate= true;
        }
        DefaultTableModel model = (DefaultTableModel)tutorTable.getModel();
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,e);
        }

        final String ID = "cseyou1";
        final String PW = "Cosc*ymfw";
        final String SERVER = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/cseyou1db";

        try
        {

            Connection con = DriverManager.getConnection(SERVER,ID,PW);
            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT * FROM cseyou1db.TutorStime");

            while(rs.next()){
                String fName = rs.getString("TSFname");
                String lName = rs.getString("TSLname");
                String date = rs.getString("TSDate");
                String time = rs.getString("TSTime");

                tuoTimeS.add(new TimeTable(fName,lName,date,time));
            }
            rs = stmt.executeQuery("SELECT * FROM cseyou1db.TutorEtime");
            while(rs.next()){
                String fName = rs.getString("TEFName");
                String lName = rs.getString("TELName");
                String date = rs.getString("TEDate");
                String time = rs.getString("TETime");

                tuoTimeE.add(new TimeTable(fName,lName,date,time));
            }
            rs = stmt.executeQuery("SELECT * FROM cseyou1db.Students");
            while(rs.next()){
                String TUID = rs.getString("TU_ID");
                String fName = rs.getString("Fname");
                String lName = rs.getString("Lname");

                students.add(new Students(TUID,lName,fName));
            }
            
            

            for(Students i: students){
                if(i.checkID(searchID)||checkID){
                    for(TimeTable j: tuoTimeS){
                        if((j.checkDate(searchDate)||checkDate) && (i.getFirst().equals(j.getFirst()) && i.getLast().equals(j.getLast()))){
                            for(TimeTable k: tuoTimeE){
                                if(j.checkDate(k.getDate()) && (j.getFirst().equals(k.getFirst()) && j.getLast().equals(k.getLast()))){
                                    
                                    model.addRow(new Object[] {i.getID(),j.getFirst(),j.getLast(),j.getDate(),j.getHours(k)});
                                }
                            }
                        }
                    }
                }
            }

        }
        catch(SQLException | ParseException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_tutorBtnActionPerformed

    private void tuteeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuteeBtnActionPerformed
        tueTimeS.clear();
        tueTimeE.clear();
        students.clear();

        String searchID = tuteeIDIN.getText();
        String searchDate = tuteeDateIN.getText();
        boolean checkID = false;
        boolean checkDate = false;
        if(searchID.isBlank() || searchID.isEmpty()){
            checkID= true;
        }
        if(searchDate.isBlank() || searchDate.isEmpty()){
            checkDate= true;
        }
        DefaultTableModel model = (DefaultTableModel)tuteeTable.getModel();
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,e);
        }

        final String ID = "cseyou1";
        final String PW = "Cosc*ymfw";
        final String SERVER = "jdbc:mysql://triton.towson.edu:3360/?serverTimezone=EST#/cseyou1db";

        try
        {

            Connection con = DriverManager.getConnection(SERVER,ID,PW);
            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery("SELECT * FROM cseyou1db.TuteeStime");

            while(rs.next()){
                String fName = rs.getString("TSEFname");
                String lName = rs.getString("TSELname");
                String date = rs.getString("TSEDate");
                String time = rs.getString("TSETime");

                tueTimeS.add(new TimeTable(fName,lName,date,time));
            }
            rs = stmt.executeQuery("SELECT * FROM cseyou1db.TuteeEtime");
            while(rs.next()){
                String fName = rs.getString("TEEFname");
                String lName = rs.getString("TEELname");
                String date = rs.getString("TEEDate");
                String time = rs.getString("TEETime");

                tueTimeE.add(new TimeTable(fName,lName,date,time));
            }
            rs = stmt.executeQuery("SELECT * FROM cseyou1db.Students");
            while(rs.next()){
                String TUID = rs.getString("TU_ID");
                String fName = rs.getString("Fname");
                String lName = rs.getString("Lname");

                students.add(new Students(TUID,lName,fName));
            }

            for(Students i: students){
                if(i.checkID(searchID)||checkID){
                    for(TimeTable j: tueTimeS){
                        if((j.checkDate(searchDate)||checkDate) && (i.getFirst().equals(j.getFirst()) && i.getLast().equals(j.getLast()))){
                            for(TimeTable k: tueTimeE){
                                if(j.checkDate(k.getDate())&& (j.getFirst().equals(k.getFirst()) && j.getLast().equals(k.getLast()))){
                                  
                                    model.addRow(new Object[] {i.getID(),j.getFirst(),j.getLast(),j.getDate(),j.getHours(k)});
                                }
                            }
                        }
                    }
                }
            }

        }
        catch(SQLException | ParseException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_tuteeBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Hour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton tuteeBtn;
    private javax.swing.JTextField tuteeDateIN;
    private javax.swing.JTextField tuteeIDIN;
    private javax.swing.JTable tuteeTable;
    private javax.swing.JButton tutorBtn;
    private javax.swing.JTextField tutorDateIN;
    private javax.swing.JTextField tutorIDIN;
    private javax.swing.JTable tutorTable;
    // End of variables declaration//GEN-END:variables
}
